# Generated by Django 2.1.5 on 2019-02-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymentry',
            old_name='author_name',
            new_name='workout_name',
        ),
        migrations.RemoveField(
            model_name='gymentry',
            name='park_name',
        ),
    ]
